version: '3'

services:
  'graphql-api':
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    container_name: 'graphql-api'
    # This service will not start until either the mongodb service is available OR thirty seconds have elapsed
    command: sh -c './scripts/wait-for.sh --timeout=30 mongodb:27017 && ./node_modules/.bin/nodemon .'
    environment:
      - MONGO_URI=mongodb://mongodb:27017/photoshare
      - CLIENT_ID=2ebb206285af39a776cc
    ports:
      - "4000:4000"
      - "9229:9229"
    # If you want local changes to update the Docker container, you can pass through project files like this:
    volumes:
      - ./:/usr/src
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: "graphql-mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./.docker/mongodb/data/db:/data/db
    ports:
      - "27017:27017"
